### ISSUE TITLE
Add Python library of equations

### ISSUE THREAD

**Issue by GrimPixel** [Blackprint/Blackprint#4]
I have an idea: keep a repository of equation codes from primary school to college. Just drag and drop, all steps of solving a question will be visualised. 

I have a Python library of some equations. I am unsure how it could be utilised as nodes here.

---

**The feature request is about:**
[ ] Blackprint Editor
[ ] Blackprint Engines

**Comment by StefansArya** [comment]
Sure,

But currently the Blackprint editor will also need the nodes to be registered for `engine-js` too, as the editor is made for browser and running in JavaScript. After you have created the nodes for `engine-js`, then you can continue porting your nodes for `engine-python`. Each engine API is similar, so it won't be so difficult if you already made the nodes for `engine-js`.

It may feels like an additional work, but currently it's the only solution that I have for bringing Blackprint to multiple languages. To make things clear, the workflow for creating nodes can be like this:

1. Run the [local](https://github.com/Blackprint/Blackprint)/[online](https://blackprint.github.io/) editor
2. Create nodes module from template [TS](https://github.com/Blackprint/template-ts) or [JS](https://github.com/Blackprint/template-js)
   -  if using online editor: you need to connect the editor to the module server
   -  if using local editor: you need to put the nodes folder in `./nodes/your-nodes`
4. Begin prototyping your nodes by using JavaScript ([engine-js](https://github.com/Blackprint/engine-js))
5. After you think your nodes is complete, you can begin porting them to Python ([engine-python](https://github.com/Blackprint/engine-python))
6. After both of them is complete, you then can easily drag and drop your nodes on the editor and export it as .json and run it in on Python or Node.js after importing your custom node modules.

In case you have some question, feel free to open a new discussion.

**Comment by GrimPixel** [comment]
I found that I probably have misunderstood. I mean, I have a function
```
def area___base__height(b, h):
	return base * height / 2
```
I would like to register it as a node “area___base__height”.

**Comment by StefansArya** [comment]
Hi, sorry I was a bit late to respond.

I have created the node you mentioned in this [repo](https://github.com/StefansArya/bp-python-node-example/tree/main/src/Triangle), and also just updated the `engine-python` itself.
I hope the repo can help you to understand on how to create a node for Python and for JavaScript.

The node registration is quite similar for both language.
For the comparison I also provide image below, the left side is JavaScript and the right side is Python.
And the code in the orange box is the code that you mentioned for the registered node.
![Nvzf5HdBrT](https://user-images.githubusercontent.com/11073373/226106464-29cfabd3-de87-43d4-9bc6-0238540b7272.jpg)

> Note:
> I was using different background for my editor.
> Node information (on mouse hover) can only be registered in JavaScript.

**Comment by GrimPixel** [comment]
This is great! An example like this is really helpful! I'm going to try it out. Thank you!
